#!/bin/bash

source "$HOME/.jlib/lib/jlib.sh"

msg() {
    bot_id="$(get_opt "telegram_bot_id")"
    chat_id="$(get_opt "telegram_chat_id")"
    msg="$1"

    ans=$(curl -s -X POST -H 'Content-Type: application/json' -d "{\"chat_id\": \"$chat_id\", \"text\": \"$msg\"}" https://api.telegram.org/bot$bot_id/sendMessage)
    username=$(echo $ans | jq -r '.result.chat.username')
    echo -e "${BGreen}Message sent to '$username'!${Color_Off}"
}

msg "$1"
