#!/bin/bash

source "$HOME/.jlib/lib/jlib.sh"

msg() {
    bot_id="$(get_opt "telegram_bot_id")"
    chat_id="$(get_opt "telegram_chat_id")"

    file="$1"
    
    ans=$(curl -s -F document=@"$file" "https://api.telegram.org/bot$bot_id/sendDocument?chat_id=$chat_id")
    username=$(echo $ans | jq -r '.result.chat.username')
    echo -e "${BGreen}File $file sent to '$username'!${Color_Off}"
}

msg "$1"
